### ISSUE TITLE
Exception when run in pre-commit ci

### ISSUE THREAD

**Issue by ibLeDy** [Lucas-C/pre-commit-hooks-safety#12]
- Run url: https://results.pre-commit.ci/run/github/271132078/1617374166.oTZJbiEtQ5WvSAQiJtgiQQ

- Full traceback:

```console
Traceback (most recent call last):
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1fa9536d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /pyupio/safety-db/master/data/insecure.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1fa9536d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/bin/safety_check", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/safety_check.py", line 38, in main
    return call_safety_check(parsed_args.files, parsed_args.ignore, parsed_args.full_report, args_rest)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/safety_check.py", line 60, in call_safety_check
    check.main(safety_args + [full_report_arg] + args_rest, prog_name="safety")
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/safety/cli.py", line 71, in check
    vulns = safety.check(packages=packages, key=key, db_mirror=db, cached=cache, ignore_ids=ignore, proxy=proxy_dictionary)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/safety/safety.py", line 138, in check
    db = fetch_database(key=key, db=db_mirror, cached=cached, proxy=proxy)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/safety/safety.py", line 121, in fetch_database
    data = fetch_database_url(mirror, db_name=db_name, key=key, cached=cached, proxy=proxy)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/safety/safety.py", line 90, in fetch_database_url
    r = requests.get(url=url, timeout=REQUEST_TIMEOUT, headers=headers, proxies=proxy)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/pc/clone/wW0pw9xyTVWbKZ_uIUTBAw/py_env-python3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /pyupio/safety-db/master/data/insecure.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1fa9536d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by graingert** [comment]
Hooks are not allowed to access the internet on pre-commit.ci, the fix is to bundle the safety db with every release of this hook

**Comment by Lucas-C** [comment]
This is not a "fix" I agree with, as the maintainer of this hook.

This pre-commit hook won't adopt a release cycle matching `safety-db` one.

I think a better way to work around this issue would be to provide the DB yourslef through the `--db` option of `safety-check`, that can be passed in `.pre-commit-config.yaml` through the `args` field.

I did not know about the https://pre-commit.ci initiative.
Maybe this hook is simply not fit to be used with that website.

**Comment by Lucas-C** [comment]
Closing this issue now.
