### ISSUE TITLE
ModuleNotFoundError: No module named 'safety.alerts'

### ISSUE THREAD

**Issue by Kurt-von-Laven** [Lucas-C/pre-commit-hooks-safety#35]
We started seeing this error intermittently just now when running the pre-commit hook at v1.3.0. It was working at 21:13 UTC today.

```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repodztrbsrf/py_env-python3.10.7/bin/safety_check", line 5, in <module>
    from pre_commit_hooks.safety_check import main
  File "/home/runner/.cache/pre-commit/repodztrbsrf/py_env-python3.10.7/lib/python3.10/site-packages/pre_commit_hooks/safety_check.py", line 12, in <module>
    from safety.cli import cli
  File "/home/runner/.cache/pre-commit/repodztrbsrf/py_env-python3.10.7/lib/python3.10/site-packages/safety/cli.py", line 13, in <module>
    from safety.alerts import alert
ModuleNotFoundError: No module named 'safety.alerts'
```

**Comment by Lucas-C** [comment]
Sorry for the delay @Kurt-von-Laven 

Have you stop using this hook?
Or else, are you still seing this issue?

**Comment by Kurt-von-Laven** [comment]
We still use this hook, and I haven't encountered that issue recently. Maybe the best thing to do is to close it, and if someone encounters it again, they can ask for it to be reopened (and ideally find a way to reproduce it).

**Comment by Lucas-C** [comment]
Alrght, closing for now then
