### ISSUE TITLE
Type error during string interpolation

### ISSUE THREAD

**Issue by ChristopherGSB** [Lucas-C/pre-commit-hooks-safety#4]
This has already been fixed in the safety library, here is the issue: https://github.com/pyupio/safety/issues/141

here is the fix: https://github.com/pyupio/safety/pull/142/files

Stacktrace: 

```
safety...................................................................Failed
hookid: python-safety-dependencies-check

Traceback (most recent call last):
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/bin/safety_check", line 11, in <module>
    sys.exit(main())
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/safety_check.py", line 8, in main
    check.main(['--full-report'] + sum((['-r', f] for f in argv), []))
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/safety/cli.py", line 71, in check
    key=key
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/safety/formatter.py", line 196, in report
    return SheetReport.render(vulns, full=full, checked_packages=checked_packages, used_db=used_db)
  File "~/.cache/pre-commit/repoqfzf4xho/py_env-python3.6/lib/python3.6/site-packages/safety/formatter.py", line 116, in render
    table.append("│ {:76} │".format(line.encode('utf-8')))
TypeError: unsupported format string passed to bytes.__format__
```

**Comment by Lucas-C** [comment]
I re-run the integration tests on Travis CI and all seem good with the latest dependencies:
https://travis-ci.org/Lucas-C/pre-commit-hooks-safety

I suggest you try to reinstall the pre-commit hooks on tour computer:
```
repo_name=git://github.com/Lucas-C/pre-commit-hooks-safety
for repo_path in $(sqlite3 ~/.cache/pre-commit/db.db "SELECT path FROM repos WHERE repo = '$repo_name';"); do rm -rf "$repo_path"; done
sqlite3 ~/.cache/pre-commit/db.db "DELETE FROM repos WHERE repo = '$repo_name';";
```

**Comment by Lucas-C** [comment]
No answer since 4 months : closing this
